name: Java CI

on: [ push, pull_request ]

jobs:
    build:
      name: Build
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v4

        - name: Set up JDK
          uses: actions/setup-java@v4
          with:
            java-version: '17'
            distribution: 'temurin'

        - name: Build with Maven
          run: mvn clean compile

    test:
      name: Test
      runs-on: ubuntu-latest
      needs: build

      steps:
        - uses: actions/checkout@v4

        - uses: actions/setup-java@v4
          with:
            java-version: '17'
            distribution: 'temurin'

        - name: Prepare Allure folder
          run: |
            echo "Create target/allure-results:"
            mkdir -p target/allure-results
            echo "Listing target/allure-results:"
            ls -la target/allure-results


#          if: always()
#          run: |
#            echo "Checking target/allure-results folder..."
#            if [ -d target/allure-results ]; then
#            echo "Folder exists!"
#            ls -la target/allure-results
#            else
#            echo "Folder target/allure-results does NOT exist!"
#            mkdir -p target/allure-results
#            echo "Created empty folder so upload step won't fail."
#            fi

        - name: Run tests
          run: | 
            mvn clean test -Dgroups=smoke

        - name: Debug Allure results
          run: |
              echo "Where am I:"
              pwd
              echo "List results in target/allure-results:"
              ls -la target/allure-results || echo "Folder is empty or missing"

        - name: Upload Allure results
          if: always()
          uses: actions/upload-artifact@v4
          with:
            name: allure-results
            path: target/allure-results

#    report:
#      name: Allure Report
#      runs-on: ubuntu-latest
#      needs: test
#
#      steps:
#        - name: Download Allure results
#          if: always()
#          uses: actions/download-artifact@v4
#          with:
#            name: allure-results
#            path: target/allure-results
#
##        - name: Install Allure CLI
##          run: |
##            wget https://github.com/allure-framework/allure2/releases/download/2.27.0/allure-2.27.0.tgz
##            tar -zxvf allure-2.27.0.tgz
##            sudo mv allure-2.27.0 /opt/allure
##            sudo ln -s /opt/allure/bin/allure /usr/bin/allure
#
#        - name: Generate Allure report
#          run: mvn allure:report
#
#        - name: Upload Allure report
#          uses: actions/upload-artifact@v4
#          with:
#            name: allure-report
#            path: allure-report

#        - name: Clean up Allure results
#          run: rm -rf allure-results

