name: Java CI

on: [ push, pull_request ]

jobs:
    build:
      name: Build and Test
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v4

        - name: Set up JDK
          uses: actions/setup-java@v4
          with:
            java-version: '17'
            distribution: 'temurin'

        - name: Build with Maven
          run: mvn clean compile

        - name: Prepare Allure folder
          run: |
            echo "Create target/allure-results:"
            mkdir -p target/allure-results
            echo "Listing target/allure-results:"
            ls -la target/allure-results

        - name: Run tests
          run: | 
            mvn clean test -Dgroups=smoke

        - name: Upload Allure Results
          uses: actions/upload-artifact@v4
          with:
            name: allure-results
            path: target/allure-results

download-artifact:
    name: Download Allure Results
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Download Allure Results
        uses: actions/download-artifact@v4
        with:
          name: allure-results
          path: target/allure-results
      - name: List Downloaded Allure Results
        run: ls -la target/allure-results
